pipeline {
    agent any

    environment {
        GOPATH = "${env.WORKSPACE}/go"
        GOBIN = "${GOPATH}/bin" 
        PATH = "${GOPATH}:${GOBIN}:/usr/local/go/bin:${env.PATH}" 
    }

    stages {
        stage('Build') {
            steps {
                echo 'Provider Building..'
                sh 'go version'
                // Add your build commands here
            }
        }
        stage('Test') {
            steps {
                echo 'Provider Testing..'
                // Add your test commands here
            }
        }
        stage('Deploy') {
            steps {
                echo 'Provider Deploying....'
                // Add your deployment commands here
            }
        }
    }
}
