pipeline {
    agent any

    tools { go '1.21' }

    stages {
        stage('Build') {
            steps {
                echo 'Provider Building..'
                sh 'go version'
            }
        }
        stage('Test') {
            steps {
                echo 'Provider Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Provider Deploying....'
            }
        }
    }
}